name: Actualizar Precios P2P
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar dependencias
        run: pip install requests pytz
        
      - name: Ejecutar Bot
        run: python bot.py
        
      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización de precios" && git push)
